### ISSUE TITLE
Anura cannot be compiled with bundled boost library

### ISSUE THREAD

**Issue by KroArtem** [anura-engine/anura#113]
Trying to build Anura b70cc28c91de2f7b1492b3df3549bda1017b65f4
There is a compilation error:

```
Building: src/formula_callable_visitor.cpp
Linking : anura
./build/filesystem.o: In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option::enum_type)':
/home/kroartem/SVN/frogatto/external/include/boost/filesystem/operations.hpp:492: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option::enum_type, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
Makefile:158: ошибка выполнения рецепта для цели «anura»
make: *** [anura] Ошибка 1
```

Here are my notes from Frogatto's IRC:

> <KroArtem> you seem to be using boost included in your repo, right?
> <KroArtem> seems like your boost is a bit outdated
> <KroArtem> here: https://github.com/boostorg/filesystem/blob/develop/include/boost/filesystem/operations.hpp
> <KroArtem> line 539, there is some difference with your bundled function declaration
> <KroArtem> also I found this: https://svn.boost.org/trac/boost/ticket/10038
> <KroArtem> probably your bundled boost is really outdated?

Unfortunately I didn't find how to use system-wide libboost-filesystem.

**Comment by rkettering** [comment]
DDR's actually having some serious issues compiling with boost right now, and it might be related.  

We've noticed you posting this, but because you keep leaving our chat room, we haven't been able to reply back right away. :(  If you're able to stick around and discuss it with him and Sirp, that'd be really awesome.  They've both put a bit of effort into solving his compilation problem, but it's kinda vexing them so far.  Anything you can add would be quite appreciated.

**Comment by hagabaka** [comment]
Last time I checked, you can just `rm -r external/include/boost` to build with system-wide boost, and that's what I had to do to avoid linking errors on Arch Linux.

If I remember correctly, @sweetkristas said on IRC that the external/headers were there mainly for building on Windows, where we also bundle dll files for the libraries. If that's the case, we should just disable it for the Linux and Mac build process. As is, we compile Anura with the bundled headers, and then try to link against the system-installed libraries, so there are bound to be errors after some library upgrades.

**Comment by KroArtem** [comment]
First of all, thanks @hagabaka for pointing me out. :) I've deleted external/include/boost and recompiled anura, now it compiles and links correctly.

Speaking about boost itself, I've already said about existing problem in the first message. It's not clear what version of boost is bundled in anura's repo but I strongly suggest updating it. :) Another thing I mentioned is that it's not clear how this directory (/include/boost) was formed, it doesn't look similar with boosts' repos.

P.S. I was in IRC for some time today but we didn't meet.

**Comment by hagabaka** [comment]
Updating the bundled headers would help for now (for your case), but it's not a good solution. This could happen again with future library upgrades, and different Linux distros upgrade libraries at different paces. For example, on Arch Linux I've had to remove the bundled boost headers to avoid linking error since August. The right thing to do is to just use the system headers to compile and link (or bundle both headers and libraries for Windows, but that's not desirable and maybe not viable for Linux).

Maybe we can set up a directory for header-only libraries such as glm and "tree-tree", which will be used for compiling on all platforms, and use external/include only for Windows.

**Comment by KroArtem** [comment]
While I partly agree with you, let's not forget that if boost 1.56 is not acceptable for compilation, library requirements should be raised not to include 1.56 version. After that, it's a good idea to use system-wide libraries as much as possible.

**Comment by hagabaka** [comment]
I think the problem isn't that boost 1.56 is incompatible with Anura, but that we are compiling to one version of headers and linking to a different version of the libraries. That's why the compilation succeeds, and only linking fails.

**Comment by hagabaka** [comment]
I've added a commit to #114 which fixes the linking error, by having Makefile look for headers in "external/header-only-libs", which contains symlinks to the bundled glm and treetree. Tested it on Arch Linux.

**Comment by HybridDog** [comment]
When l tried to compile, it aborted because it didn't find boost/align/aligned_alloc.hpp in src/kre/AlignedAllocator.hpp:29:41. l moved external/include/boost to external/header-only-libs/boost and now it works (on lubuntu).

**Comment by hagabaka** [comment]
@HybridDog the right solution is to install boost library headers from your distro (libboost1.58-dev seems to be the package you need currently). The ones in external/include happen to work for you now, but they are meant to accompany the bundled Windows/Mac libraries, and are not guaranteed to update in the same pace as your Linux distro.

**Comment by HybridDog** [comment]
l have libboost1.55-dev installed, compiling worked some weeks ago without moving the bundled boost folder.

**Comment by hagabaka** [comment]
@HybridDog it's possible to work using the bundled headers but only by coincidence. The anura source repository has bundled headers and matching versions of built libraries for Windows and Mac--not Linux. Therefore in the linking phase of your build on Linux, you are using libraries from your distro, and so you should also be using headers from your distro. Otherwise, it may work, but it may also fail during the linking phase like it did for OP of the issue and me. Whether and when you'd have the problem really depends on how fast your distro upgrades libraries and how often Anura developers update external/include. Using matching headers and libraries from your distro avoids the problem. This principle applies for compiling almost all software on Linux.

**Comment by HybridDog** [comment]
thanks, l installed libbost1.58 packages from this ppa and now it works
https://launchpad.net/~kojoley/+archive/ubuntu/boost

INSTALL tells that boost needs to be >= 1.50.0, l guess it's not up to date
https://github.com/anura-engine/anura/blob/trunk/INSTALL

**Comment by hagabaka** [comment]
You are right. boost/align/aligned_allocator seems to be new in 1.56.
