### ISSUE TITLE
[BUILD] Wrong boost sha1.hpp include in src/preferences.cpp

### ISSUE THREAD

**Issue by Houkime** [anura-engine/anura#283]
```
Building: src/preferences.cpp
src/preferences.cpp:31:10: fatal error: boost/uuid/sha1.hpp: No such file or directory
 #include <boost/uuid/sha1.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:236: build/preferences.o] Error 1

```

For modern Boost 1.68 the correct path to include is boost/uuid/detail/sha1.hpp

I can start a PR on that but I'm not sure if changing this path won't affect users with other Boost versions.
It should be integrated somehow in makefile scripts probably.

**Comment by ghost** [comment]
Thanks for warning this issue. 🙇

**Comment by ghost** [comment]
Note: https://github.com/boostorg/uuid/commit/33da3e2a5b871c3d3c0317559170dbd2e1e5bd98. Obsolete doc removed in `1.68`.

**Comment by Houkime** [comment]
Files affected are: 

* src/preferences.cpp
* src/formula_function.cpp

To quickly fix my build (successfully) I ran 

`$ sed -i 's=uuid/sha1.hpp=uuid/detail/sha1.hpp=g' src/*.cpp`

**Comment by ghost** [comment]
Note: https://github.com/boostorg/uuid/commit/3d2f7758e9e172ae471bc3717d622021b890ee04. Current doc introduced in `1.66` (didn't check in the rev graph, only trusted GitHub web UI).

**Comment by ghost** [comment]
Note: https://github.com/anura-engine/anura/blob/384a639215/external/include/boost/uuid/sha1.hpp. I suspect https://github.com/anura-engine/anura/tree/384a63921541488b7aa432497d59c14f9a2fccf2/MacOS/Frogatto.xcodeproj would be using those `/PATH/TO/ANURA/external/` hierarchy.

**Comment by ghost** [comment]
> To quickly fix my build (successfully) I ran
> 
> $ sed -i 's=uuid/sha1.hpp=uuid/detail/sha1.hpp=g' src/*.cpp

If you could trigger this by testing `uuid/detail/sha1.hpp` is found under _include directories_ but `uuid/sha1.hpp` not, I don't know any build which could break, but clones with upgraded Boost would be permanently dirty in a way I don't know how to ignore.

If you could use the same findings for defining a preprocessor label you could use to look into one path or the other, I think that would make it more verbose changes but more convenient for everybody.

**Comment by Houkime** [comment]
Successfully worked around using preprocessor commands and this answer:
https://stackoverflow.com/a/33260104

GCC 5+ and others are around for quite a while so compatibility probably won't be a real problem...
... Shouldn't be at least.

PR:
https://github.com/anura-engine/anura/pull/284

**Comment by ghost** [comment]
~~Shouldn't be. Looks nice to me.~~ Thanks!

**Comment by ghost** [comment]
I think #284 is a really great idea, just _I'm not sure we can use it right now in its current form_. Fortunately there are other (even though a lot more verbose) ways to achieve the same results as `__has_include(header-name)`.

We could change the sources in a way it wouldn't be perfectly clean, because a perfect solution wouldn't be necessary as long as all the regular target platforms and users are not impacted.

Additionally, in order to help keeping current candid Makefile free from dealing with dependency versions, as there won't be GCC update in Steam runtime some time soon, and until authors confirm the Steam runtime is or not (no longer) used by any build pipeline (!?); I'll ask to raise the Boost version requirement to `1.66` in a separate issue, after checking against the revs graph that `1.66` is really the minimum desired version.

If authors generally agree to upgrade the Boost version requirement, then I'd create a pull request targeting `trunk` (target could be later changed to a feature branch if deemed necessary) if I succeed in providing a Boost upgrade for the MacOS pipeline (see https://github.com/anura-engine/anura/commit/05f0868951d76964640e94e3b914fc62bb475abd). But it won't provide anything for the MSVS pipeline (see https://github.com/anura-engine/anura/commit/56fc9677d1b3e7e6ec0ff11450afc59ecba70eae?).
