### ISSUE TITLE
Editor window is entirely white. 

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#294]
When compiling on Ubuntu 19.10, the editor can be entered, and runs, but the window is entirely white and thus the editor can not be used.

This doesn't seem to be related to any code that was recently changed, such as the merges from Hagabaka recently, as the issue reproduces using code from the start of September. (commit 448569e26fe8ddc25c13c9382b058d237c686e6d)

To reproduce, simply run `./anura --edit`.

**Comment by DDR0** [comment]
Clarification: The game itself displays fine.

**Comment by hagabaka** [comment]
This happens for me too, and the window also becomes all white if I change the video resolution with the game menu. Since entering the editor changes the size of the window, it may be related.

The editor shows up if the game is in full screen (by starting it with `--fullscreen` then pressing Ctrl-E or `--fullscreen --edit`), although the display and mouse cursor don't line up correctly.

**Comment by hagabaka** [comment]
I added a `return false;` at the beginning of `setWindowSize` in `src/KRE/WindowManager.cpp`, and that allows editor to open without being in full screen (and disables all window resizes). So that confirms that the problem is not due to the editor but related to window resize.

**Comment by DDR0** [comment]
> I built anura with SDL2 2.0.9 and now the white screen problem is gone. The text labels are misplaced on the screen after resizing though. The latest SDL2 for my system is 2.0.10

--hagabaka in #frogatto-dev
