### ISSUE TITLE
A few questions about the building process

### ISSUE THREAD

**Issue by MetalMaxMX** [anura-engine/anura#364]
Hey! I came here wanting to ask a question about the building process (as the title says) as I am a bit confused as to why are things organized this way. 

1) During the building process, I found that you need to clone a submodule that includes a copy of imgui, a fork of it presumably. Is there any reason for that? 

2) Why was vcpkg added within the repo? I read issues and it was to solve an issue on poor text rendering on Linux, so vcpkg is there to be used up until that has been found. Has it been identified what was causing the issues? Not that I am against using vcpkg, but it does makes it harder for the 3) point that I am about to make so I'd like to know more on how progress is in there regarding it. 

3) Can this engine build with MinGW-w64? I am talking either an MSYS setup or a native MinGW setup on a Linux host, since you can cross-compile projects through a method that involves the GCC-based compiler and a few more tools on a few C++ projects here and there. I wanted to know if this is supported/been tested or anything else similar. 

Nice engine by the way! Frogatto works perfectly and all, albeit with a few slowdowns here and there when loading certain areas (presumably the requirements of the game have increased since last time at 1.3?) and a few artifacts (mostly some horizontal lines when approaching a ? symbol in the first world) but otherwise not too shabby, also liked the modules system. 

Cheers!
MetalMaxMX.

**Comment by DDR0** [comment]
Hey @MetalMaxMX!

1. It's legacy. We've got a branch that gets rid of that, which uses vcpkg to do dependency management. That branch solves debug console being garbled on Linux too.
2. We have 0 idea what's causing the text rendering issues on Linux. We assume it's a slight mismatch in package versions somewhere, but we haven't been able to pinpoint where. We still support building without vcpkg on Linux.
3. _Presumably?_ We neither test nor support this, however.

Thank you! Yeah, we've gotten quite a bit heavier in the graphics department. I think there's some low-hanging optimization fruit, but I haven't been able to pick it myself due to a bit of a time crunch on my end of the world. We know of the zooming texture issues, but we haven't been able to identify a fix for them yet unfortunately. We could use some help in that area.

Glad you liked the module system! It's one of the Good Things about the engine. :slightly_smiling_face: If you'd like to discuss with us further, I encourage you to drop by our [Discord](https://discord.gg/HhBTJWP2dR) - we should see your message much sooner then. We're not always the best at noticing when someone drops a new bug in our repo here, as you may have noticed by now. :wink:
